# Generated by Django 6.0.1 on 2026-02-06 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_deleted_at'),
        ('users', '0002_user_boarded_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following_person',
            field=models.ManyToManyField(related_name='followers', to='persons.person'),
        ),
    ]
