# Generated by Django 6.0.1 on 2026-03-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
