# Generated by Django 6.0.1 on 2026-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_platform_deleted_at'),
        ('users', '0003_user_following_user_following_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platforms',
            field=models.ManyToManyField(related_name='users', to='platforms.platform'),
        ),
    ]
