# Generated by Django 6.0.1 on 2026-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0003_user_forgot_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unseen_movies',
            field=models.ManyToManyField(blank=True, related_name='users_unseen', to='movies.movie'),
        ),
    ]
