# Generated by Django 6.0.1 on 2026-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
