# Generated by Django 6.0.1 on 2026-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user2', 'user1'], name='friendship_user2_user1_idx'),
        ),
    ]
