# Generated by Django 6.0.1 on 2026-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_friendship_friendship_user2_user1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_adult_content',
            field=models.BooleanField(default=False),
        ),
    ]
