# Generated by Django 6.0.1 on 2026-04-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_wants_adult_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wants_adult_content',
        ),
    ]
