# Generated by Django 6.0.1 on 2026-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
    ]
