# Generated by Django 6.0.1 on 2026-01-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timestamps',
        ),
    ]
