# Generated by Django 6.0.1 on 2026-03-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=32)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='genres.genre')),
            ],
            options={
                'unique_together': {('genre', 'language')},
            },
        ),
    ]
