# Generated by Django 6.0.1 on 2026-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_genretranslation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='genretranslation',
            options={'verbose_name': 'Genre Translation', 'verbose_name_plural': 'Genre Translations'},
        ),
    ]
