# Generated by Django 6.0.1 on 2026-03-13 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movietranslation_image'),
        ('reviews', '0003_comment_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at', None)), fields=('user', 'movie'), name='unique_active_review_per_user_movie', violation_error_message='Each user can only have one active review per movie.'),
        ),
    ]
