# Generated by Django 6.0.1 on 2026-02-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='isPositive',
            new_name='is_positive',
        ),
    ]
