# Generated by Django 6.0.1 on 2026-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32)),
                ('image', models.ImageField(default='person/default.png', upload_to='person')),
                ('country', models.CharField(choices=[('ES', 'Spain'), ('EN', 'England')], max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
