# Generated by Django 6.0.1 on 2026-02-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_award_deleted_at'),
        ('persons', '0002_alter_person_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='persons', to='awards.award'),
        ),
    ]
