# Generated by Django 6.0.1 on 2026-02-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
    ]
