# Generated by Django 6.0.1 on 2026-04-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_biography_person_birthday_person_deathday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('language', models.CharField(max_length=2)),
                ('biography', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='persons.person')),
            ],
            options={
                'verbose_name': 'Person Translation',
                'verbose_name_plural': 'Person Translations',
                'unique_together': {('person', 'language')},
            },
        ),
    ]
