# Generated by Django 6.0.1 on 2026-03-03 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movielist',
            unique_together={('slug', 'user')},
        ),
    ]
