# Generated by Django 6.0.1 on 2026-03-06 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielists', '0003_alter_movielist_unique_together'),
        ('movies', '0003_movietranslation_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movielist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='movielist',
            constraint=models.UniqueConstraint(fields=('slug', 'user'), name='unique_movielist_slug_user', violation_error_message='A movie list with this name already exists.'),
        ),
    ]
