# Generated by Django 6.0.1 on 2026-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielists', '0004_alter_movielist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielist',
            options={'verbose_name': 'Movie List', 'verbose_name_plural': 'Movie Lists'},
        ),
    ]
