# Generated by Django 6.0.1 on 2026-03-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielists', '0005_alter_movielist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='privacity',
            field=models.CharField(choices=[('P', 'Public'), ('F', 'Friends'), ('R', 'Private')], default='P', max_length=1),
        ),
    ]
