# Generated by Django 6.0.1 on 2026-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('persons', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField()),
                ('cover', models.ImageField(default='movies/covers/no-movie.png', upload_to='movies/covers')),
                ('actors', models.ManyToManyField(blank=True, related_name='acted_movies', to='persons.person')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='persons.person')),
                ('genres', models.ManyToManyField(related_name='movies', to='genres.genre')),
                ('platforms', models.ManyToManyField(related_name='movies', to='platforms.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
