# Generated by Django 6.0.1 on 2026-03-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movietranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/translations/covers'),
        ),
    ]
