# Generated by Django 6.0.1 on 2026-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_award_deleted_at'),
        ('movies', '0002_alter_movie_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='movies', to='awards.award'),
        ),
    ]
