# Generated by Django 6.0.1 on 2026-03-13 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movietranslation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietranslation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movietranslation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='movietranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
