# Generated by Django 6.0.1 on 2026-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movietranslation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='movietranslation',
            options={'verbose_name': 'Movie Translation', 'verbose_name_plural': 'Movie Translations'},
        ),
    ]
