# Generated by Django 6.0.1 on 2026-04-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_options_alter_movietranslation_options'),
        ('platforms', '0002_alter_platform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='movies', to='platforms.platform'),
        ),
    ]
