# Generated by Django 6.0.1 on 2026-04-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='movietranslation',
            name='title',
            field=models.CharField(),
        ),
    ]
