# Generated by Django 6.0.1 on 2026-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_slug_alter_movie_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(db_index=True),
        ),
    ]
