# Generated by Django 6.0.1 on 2026-04-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
