# Generated by Django 6.0.1 on 2026-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
