# Generated by Django 6.0.1 on 2026-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
    ]
