# Generated by Django 6.0.1 on 2026-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_platform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='platforms/'),
        ),
    ]
