# Generated by Django 6.0.1 on 2026-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(blank=True, choices=[('BP', 'Best Picture'), ('BA', 'Best Animated Feature'), ('BD', 'Best Documentary'), ('IF', 'Best International Feature'), ('MA', 'Best Actor in a Leading Role'), ('WA', 'Best Actress in a Leading Role'), ('SA', 'Best Supporting Actor'), ('SX', 'Best Supporting Actress'), ('DR', 'Best Director'), ('DD', 'Best Debut Director')])),
                ('icon', models.ImageField(default='awards/no-award.png', upload_to='awards')),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
