# Generated by Django 6.0.1 on 2026-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(blank=True, choices=[('BP', 'Best Picture'), ('BA', 'Best Animated Feature'), ('BD', 'Best Documentary'), ('IF', 'Best International Feature'), ('MA', 'Best Actor in a Leading Role'), ('WA', 'Best Actress in a Leading Role'), ('SA', 'Best Supporting Actor'), ('SX', 'Best Supporting Actress'), ('DR', 'Best Director'), ('DD', 'Best Debut Director')], max_length=2),
        ),
    ]
